server:
  port: 8888

spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/programmer_community?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


